import { generateId } from './dateUtils.js';
import { normalizePerson } from './personnelUtils.js';

export function createSamplePersonnel() {
  return [
    normalizePerson({ id: generateId(), rank: 'SSgt', lastName: 'Martinez', firstName: 'J.', name: 'Martinez, J.', phoneNumber: '831-555-2001', points: 12, lastDutyDate: '2026-05-28', section: 'Admin', nonAvailabilityInput: '', adncoNonAvailabilityInput: '', nonAvailability: [] }),
    normalizePerson({ id: generateId(), rank: 'Sgt', lastName: 'Thompson', firstName: 'R.', name: 'Thompson, R.', phoneNumber: '831-555-2002', studentType: 'MAT', points: 18, adncoPoints: 18, lastDutyDate: '2026-05-25', section: 'Operations', nonAvailabilityInput: '1-5', adncoNonAvailabilityInput: '1-5', nonAvailability: [] }),
    normalizePerson({ id: generateId(), rank: 'Cpl', lastName: 'Williams', firstName: 'K.', name: 'Williams, K.', phoneNumber: '831-555-2003', studentType: 'Academic', points: 8, adncoPoints: 8, lastDutyDate: '2026-05-30', section: 'Supply', nonAvailabilityInput: '', adncoNonAvailabilityInput: '', nonAvailability: [] }),
    normalizePerson({ id: generateId(), rank: 'Cpl', lastName: 'Davis', firstName: 'M.', name: 'Davis, M.', phoneNumber: '831-555-2004', studentType: 'Academic', points: 15, adncoPoints: 15, lastDutyDate: '2026-05-22', section: 'Communications', nonAvailabilityInput: '20-25', adncoNonAvailabilityInput: '20-25', nonAvailability: [] }),
    normalizePerson({ id: generateId(), rank: 'LCpl', lastName: 'Johnson', firstName: 'A.', name: 'Johnson, A.', phoneNumber: '831-555-2005', studentType: 'MAT', points: 6, adncoPoints: 6, lastDutyDate: '2026-05-31', section: 'Motor T', nonAvailabilityInput: '', adncoNonAvailabilityInput: '', nonAvailability: [] }),
    normalizePerson({ id: generateId(), rank: 'LCpl', lastName: 'Brown', firstName: 'T.', name: 'Brown, T.', phoneNumber: '831-555-2006', studentType: 'MAT', points: 10, adncoPoints: 10, lastDutyDate: '2026-05-27', section: 'Admin', nonAvailabilityInput: '', adncoNonAvailabilityInput: '', nonAvailability: [] }),
    normalizePerson({ id: generateId(), rank: 'PFC', lastName: 'Garcia', firstName: 'L.', name: 'Garcia, L.', phoneNumber: '831-555-2007', studentType: 'MAT', points: 4, adncoPoints: 4, lastDutyDate: '2026-06-01', section: 'Operations', nonAvailabilityInput: '', adncoNonAvailabilityInput: '', nonAvailability: [] }),
    normalizePerson({ id: generateId(), rank: 'PFC', lastName: 'Anderson', firstName: 'S.', name: 'Anderson, S.', phoneNumber: '831-555-2008', studentType: 'Academic', points: 9, adncoPoints: 9, lastDutyDate: '2026-05-29', section: 'Supply', nonAvailabilityInput: '10-14', adncoNonAvailabilityInput: '10-14', nonAvailability: [] }),
    normalizePerson({ id: generateId(), rank: 'PFC', lastName: 'Lee', firstName: 'D.', name: 'Lee, D.', phoneNumber: '831-555-2009', points: 22, lastDutyDate: '2026-05-20', section: 'Communications', nonAvailabilityInput: '', adncoNonAvailabilityInput: '', nonAvailability: [], notes: 'High points — prime supernumerary candidate' }),
    normalizePerson({ id: generateId(), rank: 'Pvt', lastName: 'Taylor', firstName: 'N.', name: 'Taylor, N.', phoneNumber: '831-555-2010', studentType: 'MAT', points: 3, adncoPoints: 3, lastDutyDate: '2026-06-02', section: 'Motor T', nonAvailabilityInput: '', adncoNonAvailabilityInput: '', nonAvailability: [] }),
  ];
}